### ISSUE TITLE
Preprocess audio inputs

### ISSUE THREAD

**Issue by Samantha-Zhan** [YilikaLoufoua/noise-suppression#5]
Prep audio data for deep learning algorithm

**Comment by Samantha-Zhan** [comment]
Done: basic filtering of clean audio, ensure the audio length and sample rate are consistent and no clipping
TO-DO: will come back in future and refine the filtering mechanism (e.g. low-activity detection)

**Comment by Samantha-Zhan** [comment]
We have decided on using the audio datastore function to retrieve downloaded audio data:
Adv.
Only retrieved when in use
Easily manipulate in a bunch
Dis.
don't support indexing of specific array; workaround: convert to tall array before use

**Comment by Samantha-Zhan** [comment]
Done research in good practices of combining clean and noise data and have a clear plan of what to do.
TO-DO:
- Conduct research on rir(room impulse response)
- Other preprocessing that can improve the quality of the combined audio (e.g. normalizing, checking glitch after combine )

**Comment by fissoreg** [comment]
>  Dis. don't support indexing of specific array; workaround: convert to tall array before use

Why is this a disadvantage? Do you ever need to index the array? From a training perspective (and it applies to preprocessing too), I believe it is enough to be able to access the data array in a streaming fashion (i.e. with an iterator interface) and possibly randomize the data order. Do you know if iterating over a datastore is possible? And is it possible to randomize the samples of a datastore?

**Comment by ericloufoua** [comment]
> Do you know if iterating over a datastore is possible? And is it possible to randomize the samples of a datastore?

It's possible to iterate over a datastore by using `read` for each audio it contains, and randomization can be done with `shuffle(ds)`. Will look more into how to bridge from current steps to training.

**Comment by Samantha-Zhan** [comment]
**Done**: low activity detection, audio normalization. Wrapping up.
**Update**: listened to Zeshan's advice and understand that preprocessing is an ongoing process, will come back and refine the preprocessing process after a rough model is built out.
