### ISSUE TITLE
Download dataset

### ISSUE THREAD

**Issue by Samantha-Zhan** [YilikaLoufoua/noise-suppression#6]
Download the speech and noise dataset by following the instructions on the [Microsoft DNS challenge repository](https://github.com/microsoft/DNS-Challenge).

**Comment by ericloufoua** [comment]
Let's look into how to do so within MATLAB!

**Comment by Samantha-Zhan** [comment]
We have decided to download data using a shell script. Due to the large size, will import portion by portion (noise+clean+rir) and swap after training finishes.
TO-DO: look into Parallel Computing Toolbox to leverage multicore processor

**Comment by ericloufoua** [comment]
We use audioDatastore to import downloaded data into MATLAB.

**Comment by fissoreg** [comment]
This issue is about download, not loading data for training (though the two things are clearly connected). @YilikaLoufoua can you reopen the issue or open a new one to keep track of progress on the download?
