### ISSUE TITLE
Conduct research and understand deep learning paper of choice

### ISSUE THREAD

**Issue by Samantha-Zhan** [YilikaLoufoua/noise-suppression#7]
Perform a literature search on speech noise suppression using deep learning.

**Comment by fissoreg** [comment]
Any updates on this? Link to chosen paper?

**Comment by ericloufoua** [comment]
I'll let @Samantha-Zhan provide an update on this since she's been more closely reading the FullSubNet paper and code.

**Comment by Samantha-Zhan** [comment]
@fissoreg Yes, we have decided on [this](https://arxiv.org/abs/2010.15508) paper after looking at all provided papers and taking Zeshan's advice into consideration. [This](https://github.com/haoxiangsnr/FullSubNet) is the researcher's GitHub repo where they implemented their training model with Python. I am now taking their code as a reference and finishing up preprocessing. Will focus on building the model next week.

**Comment by fissoreg** [comment]
Shall we put the link to the paper in the README with a short description and close this issue?
